export const REQUIRED = "Обязательно для заполнения"
export const WRONG_FIRST_NAME = "Введено не корректное имя"
export const WRONG_LAST_NAME = "Введена некорректная фамилия"
export const WRONG_CREDENTIALS = "Введен некорректный пароль или e-mail"
export const WRONG_EMAIL = "Введен некорректный e-mail"
export const WRONG_PASSWORD = "Введен некорректный пароль"
export const WRONG_COMMENT = "Введен некорректный комментарий"