export const ACTIVATION_EMAIL = "activation_email"
export const JWT_TOKEN = "jwt_token"
export const USER = "user"
export const ACTIVATED = "activated"
export const RESET_PASSWORD = "reset_password"
export const MOVE_TO_NEW_PASSWORD = "move_to_new_password"