export { RegistrationForm } from "./RegistrationForm/RegistrationForm"
export { LoginForm } from "./LoginForm/LoginForm"
export { PersonalAreaEditForm } from "./PersonalAreaEditForm/PersonalAreaEditForm"
export { NewPasswordForm } from "./NewPasswordForm/NewPasswordForm"
export { ForgetPasswordForm } from "./ForgetPasswordForm/ForgetPasswordForm"
export { ChangePasswordForm } from "./ChangePasswordForm/ChangePasswordForm"